# -*- coding: utf-8 -*-
{
    'name': 'cpabooks icon set 01 accounting community',
    'version': '14.0.0.0.0',
    'category': 'Extra Tools',
    'summary': """ accounting modules related community""",
    'description': """
                    accounting modules related community
                    """,
    'author': 'Kamrul Hasan',
    'website': "https://www.cpabooks.org/",
    'company': 'CPAbooks',
    'maintainer': 'cpabooks, Kamrul Hasan',
    'depends': [
        'base',
        'dynamic_xlsx',
        'professional_templates_v1c',
        'cpabooks_sequences',
        'ir_attachment_extend',
        'ir_attachment_s3',
        'ir_attachment_url',
        'cpabooks_chart_of_accountsc',
        'cpabooks_chart_of_accounts_v1',
        'cpabooks_admin_power',
        'cpabooks_payment_voucher',
        'acc_invoice_payment_cancel_app',
        'cpabooks_all_cancel_extend',
        'dev_invoice_multi_payment',
        'bi_print_journal_entries',
        'cpabooks_project_extendc',
        'cpabooks_delivery_slip',
        'stock_no_negative',
        'automatic_backup_db',
        'bi_subtask',
        'cpabooks_hr_extend',
        'cpabooks_tally',
        'bi_inventory_adjustment_cancel_reverse',
        'bi_order_cancel_all',
    ],
    'data': [
        # 'views/menu_icon.xml',
    ],
    'qweb': [
    ],
    'license': 'LGPL-3',
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
