version: "2"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${CHAT_PORT}:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
