# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{
    'name': 'HR Employee Payslip Reports ( PDF/Excel)',
    'version': '14.0.0.3',
    'author': 'BrowseInfo + S. M. Emrul Bahar',
    'website': 'https://www.browseinfo.in',
    'category': 'Human Resources',
    'summary': 'Employee Multiple Payslip Report print employee payslip report hr payslip report employee pay slip report mass employee payslip report print payslip report print employee payroll report print pay slip report print payslip excel report payslip xls report',
    'description': """ 
            

               Employee Multiple Payslip Report PDF & XLS  in odoo,
               Multiple payslip report pdf in odoo,
               Multiple payslip report xls in odoo,
               Salary computation Group by Salary Rule Category in odoo,
               Salary computation Group by Salary Rule in odoo,
               Print Payslip Report by PDF & XLS File Type in odoo,


    """,
    'depends':['hr_timesheet','base', 'project', 'timesheet_grid', 'eq_payslip_payment', 'hr','hr_payroll','hr_work_entry_contract','cpabooks_hr_allowance','cpabooks_payroll_overtime','hr_holidays','hr_payroll_account','hr_work_entry'],
# 'hr_contract_salary',
    'data':[
        'security/ir.model.access.csv',
        'wizard/payslip_report_wizard.xml',
        'wizard/timesheet_templates_config_result.xml',
        'report/employee_payslip_report.xml',
        'report/payslip_report_template.xml',
        'report/employee_payment_report.xml',
        'views/inherit_hr_contract.xml',
        'views/inherit_hr_payslip_line.xml',
        'views/payroll_structure.xml',
        'views/timesheet_template.xml',
        'views/timesheet_apply.xml',
        'views/hr_leave_type.xml',
        'views/hr_leave.xml',
        'views/hr_payslip_employees.xml',
        # 'views/account_asset.xml',
        'views/mej_menu.xml',
        # 'views/company.xml',
        'views/agent_routing_conf.xml',
        'views/hr_employee.xml',
        'views/employee_ctc_formula.xml',
        'views/config_me_journal_view.xml',
        # 'views/salary_python_code_setup.xml',
        'views/project_project_view_inherit.xml',
        'data/demo.xml',
        'data/create_ctc_line.xml',
        'data/salary_structure_default_value.xml',
        'data/sequences.xml',
        'data/create_config_me_journals.xml',
        'data/resource_calendar.xml',
        # 'data/hr_payroll_structure_type.xml',
        # 'data/hr_payroll_structure.xml',
        # 'data/hr_salary_rule_category.xml',
        # 'data/hr_salary_rule.xml',
        # 'data/update_salary_rules_debit_credit.xml',
        'data/timesheet_template_seq.xml',
        'wizard/absent_register_report_wizard.xml',
        'wizard/wps_report_wizard.xml',
        'wizard/employee_ctc_report_wizard.xml',
        'wizard/create_deferred_expense_wizard_view.xml',
        'wizard/project_wise_timesheet_wizard.xml',
        'wizard/timecard_report_wizard.xml',
        'report/absent_register_report.xml',
        'report/absent_register_report.xml',
        'report/timecard_report.xml',
        'security/agent_routing_domain.xml',
        ],
    'price': 15,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
    'live_test_url':'https://youtu.be/ViSC1MFaHds',
    'images':['static/description/Banner.png'],
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
