# -*- coding: utf-8 -*-
{
    'name': 'CPABooks Switchgear Custom',
    'summary': 'CPABooks Switchgear Custom',
    'description': """ Flowchart menu """,
    'category': 'Extra Tools',
    'version': '14.0.1.0.2',
    'author': 'Vishal',
    'support': 'vvgediya@gmail.com',
    'depends': [
        'crm', 'sale', 'mrp', 'stock', 'purchase', 'account', 'documents', 'project',
        'bi_material_purchase_requisitions', 'quality_control', 'cost_estimate_customer_ld',
        'sale_project', 'sale_crm','cpabooks_crm_extend'
    ],
    # 'bi_odoo_job_costing_management',
    'data': [
        'security/ir.model.access.csv',
        'wizard/create_purchase_order.xml',
        'data/ir_sequence_data.xml',
        'data/flowchart_kanban_data.xml',
        'views/crm_lead_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_bom_views.xml',
        'views/job_estimate_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        # 'views/account_move_views.xml',
        'views/purchase_order_views.xml',
        'views/quality_views.xml',
        'views/project_views.xml',
        'views/flowchart_views.xml',
        'report/job_estimate_report.xml',
        'report/mrp_report_bom_structure.xml',
        'report/mrp_production_templates.xml',
        'report/qc_label_templates.xml',
        'report/report_job_order.xml',
        'report/report_menu.xml',

    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
