# -*- coding: utf-8 -*-
{
    'name': 'xx_CPABooks Job Order Extend',
    'version': '14.0.1.0.1',
    'category': 'Project',
    'summary': """ xxx Job order extend """,
    'description': """ Job order extend """,
    'author': 'Kamrul Hasan',
    'website': "https://www.cpabooks.org/",
    'company': 'CPABooks',
    'maintainer': 'cpabooks, Kamrul Hasan',
    'depends': ['base', 'stock', 'project', 'purchase', 'crm', 'sale', 'bi_odoo_job_costing_management'],
    'data': [
        'security/ir.model.access.csv',
        'data/default_project_stage.xml',
        'views/crm_lead_views.xml',
        'views/job_cost_view.xml',
        'views/sale_order_views.xml',
        'views/project_task.xml',
        'views/project_task_kanban.xml',
        'views/project_defaul_task.xml',
        'views/purchase_order.xml',
        'report/technical_submittal_report_template.xml',
        'report/internal_order_report_template.xml',
        'report/report_menu.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
