# -*- coding: utf-8 -*-
# License LGPL-3.0 or later (https://opensource.org/licenses/LGPL-3.0).
#
# This software and associated files (the "Software") may only be used (executed,
# modified, executed after modifications) if you have purchased a valid license
# from the authors, typically via Odoo Apps, or if you have received a written
# agreement from the authors of the Software (see the COPYRIGHT section below).
#
# You may develop Odoo modules that use the Software as a library (typically
# by depending on it, importing it and using its resources), but without copying
# any source code or material from the Software. You may distribute those
# modules under the license of your choice, provided that this license is
# compatible with the terms of the Odoo Proprietary License (For example:
# LGPL, MIT, or proprietary licenses similar to this one).
#
# It is forbidden to publish, distribute, sublicense, or sell copies of the Software
# or modified copies of the Software.
#
# The above copyright notice and this permission notice must be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#########COPYRIGHT#####
# © 2017 Bernard K Too<bernard.too@optima.co.ke>
from num2words import num2words

from odoo import _, api, fields, models


class PO(models.Model):
    _inherit = ["purchase.order"]

    @api.onchange('company_id')
    def get_default_approve_and_prepared_by(self):
        for rec in self:
            last_val = self.env['sale.order'].search([], limit=1)
            if last_val:
                rec.approve_by = last_val.approve_by
                rec.prepared_by = last_val.prepared_by
            else:
                rec.approve_by = False
                rec.prepared_by = False

    vendor_vat = fields.Char('Vendor Tax Id.', related='partner_id.vat')
    company_vat = fields.Char('Company Tax Id.', related='company_id.vat')
    #signature
    approve_by = fields.Many2one('res.users', 'Approved By')
    prepared_by = fields.Many2one('res.users', 'Prepared By')
    stamp = fields.Binary('stamp', compute='_get_stamp')
    # note = fields.Text(default=lambda self: self.get_notes())

    # def get_notes(self):
    #     return "We hope our quotation are in line with your requirements & look forward to hear from you\n\n\n\n\nFor," + self.env.company.name

    def _get_stamp(self):
        for rec in self:
            rec.stamp = rec.approve_by.user_stamp or rec.prepared_by.user_stamp or False





    @api.onchange('partner_id')
    def onchange_partner_style(self):
        self.po_style = self.partner_id.style or self.env.user.company_id.df_style or self.env.ref(
            'professional_templates_v1.df_style_for_all_reports').id
        self.rfq_style = self.partner_id.style or self.env.user.company_id.df_style or self.env.ref(
            'professional_templates_v1.df_style_for_all_reports').id

    po_style = fields.Many2one('report.template.settings',
                               'PO Style',
                               help="Select Style to use when printing the PO",
                               default=lambda self: self.partner_id.style or
                               self.env.user.company_id.df_style)
    amount_words = fields.Char(
        'Amount in Words:',
        help=
        "The total amount in words is automatically generated by the system..few languages are supported currently",
        compute='_compute_num2words')

    def _compute_num2words(self):
        for rec in self:
            style = rec.po_style or rec.partner_id.style or rec.env.user.company_id.df_style or rec.env.ref(
                'professional_templates_v1.df_style_for_all_reports')
            rec.amount_words = "Disabled."
            currency_id = rec.currency_id if rec.currency_id else self.env.company.currency_id
            if style and style.aiw_report:
                if currency_id:
                    rec.amount_words = str(currency_id.amount_to_text(rec.amount_total)).replace('And', 'and')

    #Signature
    def get_signature(self):
        get_signature_data=self.env['signature.setup'].search([('model','=','purchase.order'),('company_id','=',self.env.company.id)],limit=1,order="id desc")
        return  get_signature_data
